language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
install:
  # new bundler install needed by ruby2.6(!)
  - gem install bundler
  - bundle config set path 'vendor/bundle'
  - bundle install --path vendor/bundle --jobs=3 --retry=3 --without=development
