name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ['3.0', '3.1', '3.2', '3.3', '3.4']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Run tests
      run: |
        bundle config set path 'vendor/bundle'
        bundle config set --local without development rubocop
        bundle config set --local with test
        bundle install
        bundle exec rake
